# -*- coding: utf-8 -*-
"""Day3_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TVNJVRa6O0hSv_5Q33Y4wSNtJIgtkzcR

# Day 3 – Agent with Tool Integration

## Objective
This notebook demonstrates an AI agent capable of:
- Selecting between direct answering and tool usage
- Using an external calculator tool
- Showing reasoning traces
- Performing multi-step decision making
"""

!pip install -U langchain langchain-core langchain-community transformers

from langchain_core.tools import Tool
from langchain_community.llms import HuggingFacePipeline
from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    max_new_tokens=200
)

llm = HuggingFacePipeline(pipeline=pipe)

def calculator_tool(expression):
    return str(eval(expression))

calculator = Tool(
    name="Calculator",
    func=calculator_tool,
    description="Useful for solving math calculations"
)

def simple_agent(question):
    print("Agent reasoning started...")

    # Decide whether tool is needed
    if any(char.isdigit() for char in question):
        print("Tool selected: Calculator")
        expression = question.replace("What is", "").replace("?", "")
        result = calculator.run(expression)
        return f"Final Answer (Tool Output): {result}"

    else:
        print("Answering directly with LLM")
        return llm.invoke(question)

print(simple_agent("What is 25 * 12 + 8?"))

print(simple_agent("What is Artificial Intelligence?"))

"""## Why Tool Usage Improves Reliability

The agent decides whether to use a tool based on the query.

- Mathematical queries → Calculator tool
- General questions → LLM direct response

This improves reliability because tools handle tasks that LLMs may answer incorrectly.
"""